create table if not exists admin_audit_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  entity text not null,
  entity_id bigint,
  detail jsonb,
  performed_by text,
  created_at timestamptz not null default now()
);


