-- News 테이블 생성
CREATE TABLE IF NOT EXISTS public.news (
    news_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title character varying(255) NOT NULL,
    slug character varying(255) NOT NULL UNIQUE,
    category character varying(50) NOT NULL, -- 'press', 'tech', 'project', 'announcement'
    summary text,
    content text NOT NULL,
    thumbnail_url text,
    author character varying(100),
    published_date timestamptz,
    is_published boolean DEFAULT FALSE NOT NULL,
    view_count integer DEFAULT 0,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_news_slug ON public.news (slug);
CREATE INDEX IF NOT EXISTS idx_news_published ON public.news (is_published, published_date DESC);
CREATE INDEX IF NOT EXISTS idx_news_category ON public.news (category);

-- RLS (Row Level Security) 활성화
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

-- 모든 사용자가 발행된 뉴스를 읽을 수 있도록 정책 설정
CREATE POLICY "Anyone can view published news"
ON public.news
FOR SELECT
USING (is_published = TRUE);

-- 인증된 사용자만 뉴스를 생성/수정/삭제할 수 있도록 정책 설정 (관리자 전용)
CREATE POLICY "Authenticated users can manage news"
ON public.news
FOR ALL
USING (auth.role() = 'authenticated');

-- 샘플 데이터 삽입
INSERT INTO public.news (title, slug, category, summary, content, author, published_date, is_published) VALUES
('ysterkorea, 차세대 LED 디스플레이 기술 개발 완료', 'next-gen-led-display-tech', 'tech', 
 '에너지 효율을 30% 향상시킨 차세대 LED 디스플레이 기술 개발에 성공했습니다.',
 '# 차세대 LED 디스플레이 기술 개발

ysterkorea는 지난 2년간의 연구 개발 끝에 에너지 효율을 30% 향상시킨 차세대 LED 디스플레이 기술 개발에 성공했다고 발표했습니다.

## 주요 특징

- 에너지 효율 30% 향상
- 밝기 20% 증가
- 수명 50% 연장
- 친환경 소재 사용

이번 기술 개발로 ysterkorea는 업계 선도 기업으로서의 입지를 더욱 공고히 할 것으로 예상됩니다.',
 'ysterkorea', NOW() - INTERVAL '5 days', TRUE),

('서울 강남구 대형 빌딩 미디어 파사드 프로젝트 수주', 'gangnam-media-facade-project', 'project',
 '서울 강남구에 위치한 대형 빌딩의 미디어 파사드 프로젝트를 성공적으로 수주했습니다.',
 '# 강남 대형 빌딩 미디어 파사드 프로젝트

ysterkorea가 서울 강남구 테헤란로에 위치한 대형 빌딩의 미디어 파사드 프로젝트를 수주했습니다.

## 프로젝트 개요

- 위치: 서울 강남구 테헤란로
- 규모: 1,500㎡
- 공사 기간: 2024년 3월 ~ 2024년 6월
- 예산: 비공개

이번 프로젝트는 최신 LED 디스플레이 기술을 활용하여 건물 외관을 혁신적으로 변화시킬 예정입니다.',
 'ysterkorea', NOW() - INTERVAL '10 days', TRUE),

('[보도자료] ysterkorea, ISO 14001 환경경영시스템 인증 획득', 'iso-14001-certification', 'press',
 'ysterkorea가 국제 표준 환경경영시스템 인증인 ISO 14001을 획득했습니다.',
 '# ysterkorea, ISO 14001 인증 획득

## 회사 개요

ysterkorea(대표 홍길동)는 최근 국제 표준화기구(ISO)로부터 환경경영시스템 인증인 ISO 14001을 획득했다고 밝혔습니다.

## 인증 의미

ISO 14001은 기업의 환경 경영 체계가 국제 표준에 부합함을 인증하는 것으로, ysterkorea의 친환경 경영 의지를 대외적으로 인정받은 것입니다.

## 향후 계획

ysterkorea는 이번 인증을 계기로 더욱 적극적인 환경 보호 활동을 펼쳐나갈 계획입니다.

## 문의

- 홍보팀: pr@ysterkorea.com
- 전화: 02-1234-5678',
 'ysterkorea PR팀', NOW() - INTERVAL '3 days', TRUE);
