-- Popups 테이블 생성
CREATE TABLE IF NOT EXISTS public.popups (
    popup_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title character varying(255) NOT NULL,
    content text NOT NULL,
    image_url text,
    link_url text,
    link_text character varying(100),
    start_date timestamptz NOT NULL,
    end_date timestamptz NOT NULL,
    is_active boolean DEFAULT TRUE NOT NULL,
    priority integer DEFAULT 0, -- 숫자가 높을수록 우선순위 높음
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_popups_active ON public.popups (is_active, priority DESC);
CREATE INDEX IF NOT EXISTS idx_popups_dates ON public.popups (start_date, end_date);

-- RLS (Row Level Security) 활성화
ALTER TABLE public.popups ENABLE ROW LEVEL SECURITY;

-- 모든 사용자가 활성화된 팝업을 볼 수 있도록 정책 설정
CREATE POLICY "Anyone can view active popups"
ON public.popups
FOR SELECT
USING (
    is_active = TRUE 
    AND start_date <= NOW() 
    AND end_date >= NOW()
);

-- 인증된 사용자만 팝업을 관리할 수 있도록 정책 설정
CREATE POLICY "Authenticated users can manage popups"
ON public.popups
FOR ALL
USING (auth.role() = 'authenticated');

-- 샘플 데이터 삽입 (현재 날짜 기준으로 활성화)
INSERT INTO public.popups (title, content, link_url, link_text, start_date, end_date, is_active, priority) VALUES
('2024년 신제품 출시 안내', 
 '차세대 LED 디스플레이 제품이 출시되었습니다. 에너지 효율 30% 향상, 밝기 20% 증가!',
 '/solutions',
 '제품 보러가기',
 NOW() - INTERVAL '1 day',
 NOW() + INTERVAL '30 days',
 TRUE,
 10);
