-- Solutions 테이블 생성
CREATE TABLE IF NOT EXISTS public.Solutions (
    solution_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title character varying(255) NOT NULL,
    slug character varying(255) NOT NULL UNIQUE,
    short_description text,
    technical_specs jsonb,
    business_value text,
    is_active boolean DEFAULT TRUE NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL
);

-- URL 검색 효율을 위한 인덱스 추가
CREATE INDEX IF NOT EXISTS idx_solutions_slug ON public.Solutions (slug);

-- 활성 상태 필터링을 위한 인덱스 추가
CREATE INDEX IF NOT EXISTS idx_solutions_is_active ON public.Solutions (is_active);

